import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  mydocSideBar: [
    {
      type: "category",
      label: "杂技", // 链接标签
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "React Filber 解析",
          id: "fe/ReactFilber",
        },
        {
          type: "doc",
          label: "Debug Nodejs",
          id: "fe/debugNode",
        },
        {
          type: "doc",
          label: "Nodejs Cli 工具开发",
          id: "fe/node_cli",
        },
      ],
    },
    {
      type: "category",
      label: "算法", // 链接标签
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "归并排序",
          id: "leetcode/mergeSort",
        },
      ],
    },
    {
      type: "category",
      label: "Nestjs", // 链接标签
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "start",
          id: "nestjs/start",
        },
      ],
    },
    {
      type: "category",
      label: "Nextjs", // 链接标签
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "start",
          id: "nextjs/start",
        },
      ],
    },
  ],
};

export default sidebars;
