name: Deploy GitHub Pages

# 触发条件：推送到 main 分支时自动执行（如果你的主分支叫 master，请改成 master）
on:
  push:
    branches:
      - main

# 运行的任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # GitHub 提供的 Ubuntu 虚拟机
    steps:
      # 1️⃣ 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 Node.js（建议固定版本，Docusaurus 3.x 可以用 Node 18 或 20）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm" # 缓存 node_modules 加快后续构建

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: npm ci
        # 如果你用 yarn，可改成：
        # run: yarn install --frozen-lockfile

      # 4️⃣ 构建 Docusaurus 静态文件
      - name: Build website
        run: npm run build
        # 相当于执行 docusaurus build，产物会生成到 build/ 目录

      # 5️⃣ 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
